version: 2

models:
  - name: gold_customer_order_summary
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique
      - name: total_orders
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: gold_product_performance
    columns:
      - name: part_key
        tests:
          - not_null
          - unique
      - name: net_revenue
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
