name: dbt_data_quality
version: 1.0.0
config-version: 2

profile: dbt_data_quality

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_data_quality:
    +materialized: view
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
